<?php

/**
 * @file
 * Shows Penn State Search block for Drupal
 */

/**
 * Implements hook_init() called when any page is loaded.
 * Used to insert required JS and CSS files for Search into the page's head.
 */
function psu_drupal_search_block_init() {
	drupal_add_js( drupal_get_path( 'module', 'psu_drupal_search_block') . '/js/search_box.js' );
	drupal_add_css( drupal_get_path( 'module', 'psu_drupal_search_block') . '/css/search_block.css' );
}

/**
 * Implements hook_block_info().
 */
function psu_drupal_search_block_block_info() {
  $blocks['psu_drupal_search_block'] = array(
    'info' => t('Penn State Search block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  
  return $blocks;
}

/**
 * Implements hook_enable() called when the module is enabled.
 */
function psu_drupal_search_block_enable() { }

/**
 * Implements hook_block_configure().
 */
function psu_drupal_search_block_block_configure($delta = '') {


}

/**
 * Implements hook_block_save().
 */
function psu_drupal_search_block_block_save($delta = '', $edit = array()) {

}

/**
 * Implements hook_block_view().
 */
function psu_drupal_search_block_block_view($delta = '') {
  switch ($delta) {
    case 'psu_drupal_search_block':
      if (user_access('access content')) {
      	// Load the HTML code for the PSU Search form directly from an extermal html file.
		$file_path = getcwd() . '/' . drupal_get_path('module', 'psu_drupal_search_block') . '/search_block.html';
		$code = file_get_contents( $file_path );
	
		// Disable the title of the block
		$block['subject'] = '<none>';
	
		// Paste in content from HTML file
		$block['content'] = $code;
      }
    }
    
  return $block;
}